apiVersion: v1
kind: Service
metadata:
  name: servicea
spec:
  selector:
    app: servicea
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer  # AWS will create an external Load Balancer
