apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
        - name: serviceb
          image: serviceb:latest
          ports:
            - containerPort: 8085

---

apiVersion : v1
kind: Service
metadata:
  name: serviceb
spec:
  selector:
    app: serviceb
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
